try:
    num = 10
    print(num)
    raise ValueError
except:
    print("Exception occurred .... Program Terminating...")
